project:
  title: "FAO Climate Change Risks to Fed Mariculture"
  type: default
  output-dir: documentation-htmls
  render: 
    - index.qmd
    - documentation-qmds/00_model_function_demonstration.qmd
    - documentation-qmds/01_choosing_species.qmd
    - documentation-qmds/02_01_check_species_atlantic_salmon.qmd
    - documentation-qmds/04_assigning_locations.qmd

format:
  html:
    theme: simplex
    css: ["resources/extra.css"]
    embed-resources: true
    lightbox: true
    code-fold: true
    code-overflow: wrap
    toc: true
    toc-expand: true
    toc-location: left
    toc-depth: 4
    lang: en-GB
    grid:
      sidebar-width: 300px
      body-width: 1250px
      margin-width: 200px
      gutter-width: 2em
    mermaid:
      theme: default
        
execute:
  eval: true
  cache: true # quarto render --cache-refresh

bibliography: ["resources/references.bib", "resources/manual-refs.bib"]

knitr: 
  opts_chunk:
    fig.align: center
    fig.height: 7
    fig.width: 9
